modLoader="javafml" #mandatory
loaderVersion="[27,)"
#issueTrackerURL="http://my.issue.tracker/"

[[mods]]
modId="tanktest"
version="${file.jarVersion}"
displayName="Tank Test"
updateJSONURL="http://myurl.me/"
displayURL="http://example.com/"
logoFile="examplemod.png"
credits="The Forge and FML guys, for making forge"
authors="KingIceCream"
description="Just A Tank Test"

[[dependencies.tanktest]] #optional
    modId="forge"
    mandatory=true
    versionRange="[27,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.tanktest]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.3]"
    ordering="NONE"
    side="BOTH"